# Generated by Django 5.0.6 on 2024-05-30 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_newscategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('main_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoty_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.newscategory')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
