# Generated by Django 5.0.6 on 2024-06-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productmodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'NewsCategory', 'verbose_name_plural': 'NewsCategories'},
        ),
    ]
